# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 290641c005b7e01a64bcdf944b7699fb22d3f50c35f375a55f71c0e057d78e4e008fc23fe67da4febccddec6469a684ffe7c0d040ee438ec5c3a68e689a6e2b6

test:
  secret_key_base: 7f814688639eabf4d2b645d69e4e0dd36d48375bd1bde8988696900971a70d2f0b43e71d6f646e6465834aefd5305e60c6fc3f8e646b9a9dbc1b726d831687d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
